Repository eclipse-sw360/sw360-frontend, pull requests merged in 2023-05, with the labels that each got.

#21 Add initial base project docs
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation, needs codes review

#29 feat(ui): Initial push for home and project page
  .licenserc.yaml
  defaultValues/defaultValuesHome-MyComponents.json
  defaultValues/defaultValuesHome-MyProjects.json
  defaultValues/defaultValuesHome-MyRecentComponents.json
  defaultValues/defaultValuesHome-MyRecentReleases.json
  defaultValues/defaultValuesHome-MySubscriptions.json
  defaultValues/defaultValuesHome-MyTaskAssignments.json
  defaultValues/defaultValuesHome-MyTaskSubmissions.json
  defaultValues/defaultValuesProjects-ProjectsList.json
  mockData/mockProjectData.json
  package.json
  public/images/logo-edited.svg
  public/images/profile.svg
  src/components/AddAdditionalRoles.tsx
  src/components/AddKeyValue.tsx
  src/components/Navbar.tsx
  src/components/SearchUsersModal.tsx
  src/components/SearchVendorsModal/Vendor.tsx
  src/components/SearchVendorsModal/index.tsx
  src/components/SelectCountry.tsx
  src/components/footer.tsx
  src/components/layout.tsx
  src/css/AddKeyValue.module.css
  src/css/AddProjects.module.css
  src/css/SearchModal.module.css
  src/css/footer.module.css
  src/css/home.module.css
  src/css/navbar.module.css
  src/css/projects.module.css
  src/pages/[projects]/[add]/administration.tsx
  src/pages/[projects]/[add]/linkedProjects.tsx
  src/pages/[projects]/[add]/summary.tsx
  src/pages/[projects]/index.tsx
  src/pages/_document.tsx
  src/pages/home.tsx
  src/services/home.service.ts
  src/services/projects.service.ts
  src/utils/env.ts
  src/utils/pagination/Pagination.tsx
  src/utils/pagination/pagination.module.css
  src/utils/pagination/usePagination.tsx
  src/utils/table-builder/buildTable.module.css
  src/utils/table-builder/buildTables.tsx
  src/utils/table-schema/homePageTableSchemas.tsx
  src/utils/table-schema/projectTableSchema.tsx
Labels: needs codes review

#24 Upgrade to Next.js 13.4
  .eslintrc.json
  .gitignore
  package.json
  tsconfig.json
Labels: ready

#30 Fix build errors and add build check
  .github/workflows/build.yaml
  .licenserc.yaml
  next.config.js
  package.json
  src/components/AddKeyValue.tsx
  src/components/Navbar.tsx
  src/components/SelectCountry.tsx
  src/components/component/advance.search.tsx
  src/components/component/delete.component.dialog.tsx
  src/components/component/list.components.tsx
  src/object-types/Constants.ts
  src/pages/[projects]/[add]/administration.tsx
  src/pages/[projects]/[add]/linkedProjects.tsx
  src/pages/[projects]/index.tsx
  src/pages/components/index.tsx
  src/services/auth.service.ts
  src/services/home.service.ts
  src/services/projects.service.ts
  src/utils/api/api.util.ts
  src/utils/common.utils.ts
  src/utils/pagination/Pagination.tsx
  src/utils/pagination/usePagination.tsx
Labels: enhancement, ready

#31 Prepare production docker release
  .devcontainer/devcontainer.json
  .dockerignore
  .github/workflows/docker_deploy.yml
  Dockerfile
  next.config.js
Labels: enhancement, ready

#32 Unify codes
  .prettierrc.js
  CONTRIBUTING.md
  README.md
  package.json
  public/images/logo-edited.svg
  public/locales/en/common.json
  src/assets/images/profile.svg
  src/components/Footer/index.tsx
  src/components/Navbar.tsx
  src/components/ProfileDropdown/index.tsx
  src/components/SW360Navbar/index.tsx
  src/components/component/list.components.tsx
  src/components/header.tsx
  src/components/layout.tsx
  src/css/navbar.module.css
  src/pages/index.tsx
  src/services/home.service.ts
  src/services/projects.service.ts
  src/utils/env.ts
Labels: ready, breaking change

#39 Enable hard linting
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  package.json
  tsconfig.json
Labels: ready

#44 Cache npm dependencies
  .github/deny_list.sh
  .github/workflows/build.yaml
  .gitignore
  package-lock.json
Labels: ready

#48 Component typing
  src/app/[locale]/home/components/MyComponentsWidget.tsx
  src/app/[locale]/home/components/MyProjectsWidget.tsx
  src/app/[locale]/home/components/MyTaskAssignmentsWidget.tsx
  src/app/[locale]/home/components/MyTaskSubmissionsWidget.tsx
  src/components/header/Header.tsx
  src/services/home.service.ts
  tsconfig.json
  types/image.d.ts
Labels: ready

#50 Projects page component based
  src/app/[locale]/projects/page.tsx
  src/components/SW360AdvancedSearch/SW360AdvancedSearch.tsx
  src/components/SW360AdvancedSearch/sw360advancedsearch.module.css
  src/utils/pagination/Pagination.tsx
  src/utils/pagination/pagination.module.css
  src/utils/pagination/usePagination.tsx
  src/utils/sw360fetchdata.ts
  src/utils/table-builder/buildTable.module.css
  src/utils/table-builder/buildTables.tsx
  src/utils/table-schema/projectTableSchema.tsx
Labels: ready

#51 Prevent fetch loop
  src/app/[locale]/home/components/MyProjectsWidget.tsx
  src/app/[locale]/home/components/sw360fetchprojectdata.service.ts
  src/app/[locale]/home/home.service.ts
Labels: ready
